import type { Playlist } from "./types"

export const playlists: Playlist[] = [
  {
    id: "sun-near-me",
    title: "Sun Near Me",
    description: "A collection of sun-drenched tracks for your daily journey.",
    coverImage: "/images/sun near me spotify.jpg",
    spotifyUrl: "https://open.spotify.com/playlist/5nH4uBvM0p6BSCRFjy7EnV",
    tags: ["sunny", "uplifting", "vibrant", "bright", "energetic"],
  },
  {
    id: "plunderphonic-sun-near-me",
    title: "Plunderphonic Sun Near Me",
    description: "A collage of sun-drenched samples and global grooves for adventurous listening.",
    coverImage: "/images/snm1.png",
    spotifyUrl: "https://open.spotify.com/playlist/45XyLuq3HNOLyIH17xeg6Z?si=e622565982594de5",
    tags: ["plunderphonic", "eclectic", "global", "adventurous", "experimental"],
  },
  {
    id: "droney-sun-near-me",
    title: "Droney Sun Near Me",
    description: "Longform, meditative, and atmospheric tracks for deep sun gazing or zoning out.",
    coverImage: "/images/snm2.png",
    spotifyUrl: "https://open.spotify.com/playlist/3SzWRovi8eCIrGoHqqJGez?si=7c741f56455049ad",
    tags: ["drone", "ambient", "meditative", "atmospheric", "calm"],
  },
  {
    id: "groovy-sun-near-me",
    title: "Groovy Sun Near Me",
    description: "Funky, upbeat, and danceable tracks to keep your sun shining and your feet moving.",
    coverImage: "/images/snm3.png",
    spotifyUrl: "https://open.spotify.com/playlist/4wrfRjXLc8Hb9IxV0h5XWn?si=7ce43a645a3d457f",
    tags: ["groove", "funk", "dance", "upbeat", "energetic"],
  },
  {
    id: "fun-sun-near-me",
    title: "Fun Sun Near Me",
    description: "Playful, quirky, and joyful tunes for a lighthearted day in the sun.",
    coverImage: "/images/snm4.png",
    spotifyUrl: "https://open.spotify.com/playlist/5A8WxUmze5lAsZxNYWNEFd?si=5f770be09ab3416d",
    tags: ["fun", "quirky", "playful", "joyful", "light"],
  },
  {
    id: "fonk-sun-near-me",
    title: "Fonk Sun Near Me",
    description: "Heavy bass, funky beats, and sun-drenched jams for a fonky afternoon.",
    coverImage: "/images/snm5.png",
    spotifyUrl: "https://open.spotify.com/playlist/3zMRfn7tAUPfupqu4OC0Oh?si=bf0c4337ced94987",
    tags: ["funk", "bass", "jam", "afternoon", "groove"],
  },
  {
    id: "trip-hop-sun-near-me",
    title: "Trip Hop Sun Near Me",
    description: "Laid-back, trippy, and sun-soaked beats for a chill session.",
    coverImage: "/images/snm6.png",
    spotifyUrl: "https://open.spotify.com/playlist/2oUqbU8g5wLrOkTVRkW9PL?si=1d5f8d15977946ec",
    tags: ["trip-hop", "chill", "beats", "laid-back", "electronic"],
  },
  {
    id: "noisy-sun-near-me",
    title: "Noisy Sun Near Me",
    description: "Experimental, noisy, and boundary-pushing tracks for a wild sun adventure.",
    coverImage: "/images/snm7.png",
    spotifyUrl: "https://open.spotify.com/playlist/6yigwlBXTUOXa2lLzPuk4P?si=d3c10c88eb3e409a",
    tags: ["experimental", "noise", "wild", "adventure", "avant-garde"],
  },
  {
    id: "psytrance-sun-near-me",
    title: "Psytrance Sun Near Me",
    description: "Psychedelic trance and high-energy beats for a sun-powered dance journey.",
    coverImage: "/images/snm8.png",
    spotifyUrl: "https://open.spotify.com/playlist/2gPqLI0nLGwQ5VGYdme27V?si=576da8adfd9c436d",
    tags: ["psytrance", "psychedelic", "dance", "energy", "electronic"],
  },
  {
    id: "kraut-prog-sun-near-me",
    title: "Kraut Prog Sun Near Me",
    description: "Progressive, cosmic, and hypnotic jams for a mind-expanding sun trip.",
    coverImage: "/images/snm9.png",
    spotifyUrl: "https://open.spotify.com/playlist/1w6T7d8sQY218QKKFMQjSf?si=0db219e8f58e4a66",
    tags: ["krautrock", "prog", "cosmic", "hypnotic", "experimental"],
  },
  {
    id: "garage-sun-near-me",
    title: "Garage Sun Near Me",
    description: "Raw, energetic, and sun-baked garage rock for a lively day.",
    coverImage: "/images/snm10.png",
    spotifyUrl: "https://open.spotify.com/playlist/0xeK04fvXzPpwmHKqpssEo?si=95d4fa62ade649a0",
    tags: ["garage", "rock", "energetic", "raw", "gritty"],
  },
  {
    id: "hazy-sun-near-me",
    title: "Hazy Sun Near Me",
    description: "Dreamy, lo-fi, and hazy tracks for a mellow sun mood.",
    coverImage: "/images/snm11.png",
    spotifyUrl: "https://open.spotify.com/playlist/7fSGsBv7sh2VbUx2CpnjX9?si=cc12795fbde54159",
    tags: ["hazy", "lo-fi", "dreamy", "mellow", "ambient"],
  },
  {
    id: "disco-sun-near-me",
    title: "Disco Sun Near Me",
    description: "Disco grooves and sunny dancefloor anthems for a sparkling day.",
    coverImage: "/images/snm12.png",
    spotifyUrl: "https://open.spotify.com/playlist/3wLYpLjv1nIZNcVlZQDOeV?si=6995f471c1984e50",
    tags: ["disco", "dance", "sparkle", "groove", "vintage"],
  },
  {
    id: "psychedelic-sun-near-me",
    title: "Psychedelic Sun Near Me",
    description: "Colorful, mind-bending, and sun-drenched psychedelic sounds.",
    coverImage: "/images/snm13.png",
    spotifyUrl: "https://open.spotify.com/playlist/2boIfOwUDJFEXUZGQXgwcW?si=b982fe58887b491b",
    tags: ["psychedelic", "colorful", "mind-bending", "sunny", "experimental"],
  },
  // {
  //   id: "sunrise",
  //   title: "Sunrise",
  //   description: "Start your day with these uplifting tracks.",
  //   coverImage: "/images/snm14.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX4PP3DA4J0N8",
  //   tags: ["morning", "sunrise", "uplifting", "fresh", "energetic"],
  // },
  // {
  //   id: "sunset",
  //   title: "Sunset",
  //   description: "Wind down your day with these peaceful melodies.",
  //   coverImage: "/images/snm15.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX6FpkH3e3JwS",
  //   tags: ["evening", "sunset", "peaceful", "calm", "relaxing"],
  // },
  // {
  //   id: "midday",
  //   title: "Midday",
  //   description: "Keep your energy up with these vibrant tracks.",
  //   coverImage: "/images/snm16.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX8NTLI2TtZa6",
  //   tags: ["day", "energetic", "vibrant", "bright", "active"],
  // },
  // {
  //   id: "night",
  //   title: "Night",
  //   description: "Stargaze and dream with these ambient sounds.",
  //   coverImage: "/images/snm17.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX1n9whBbBKoL",
  //   tags: ["night", "ambient", "dreamy", "cosmic", "calm"],
  // },
  // {
  //   id: "beach",
  //   title: "Beach",
  //   description: "Feel the ocean breeze with these coastal vibes.",
  //   coverImage: "/images/snm18.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX6FpkH3e3JwS",
  //   tags: ["beach", "ocean", "summer", "coastal", "relaxing"],
  // },
  // {
  //   id: "mountain",
  //   title: "Mountain",
  //   description: "Elevate your spirits with these high-altitude tunes.",
  //   coverImage: "/images/snm19.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX1n9whBbBKoL",
  //   tags: ["mountain", "elevation", "nature", "vast", "inspiring"],
  // },
  // {
  //   id: "forest",
  //   title: "Forest",
  //   description: "Connect with nature through these woodland melodies.",
  //   coverImage: "/images/snm20.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX4PP3DA4J0N8",
  //   tags: ["forest", "nature", "peaceful", "organic", "natural"],
  // },
  // {
  //   id: "desert",
  //   title: "Desert",
  //   description: "Experience the vastness of desert landscapes through sound.",
  //   coverImage: "/images/snm21.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX8NTLI2TtZa6",
  //   tags: ["desert", "vast", "warm", "spacious", "atmospheric"],
  // },
  // {
  //   id: "city",
  //   title: "City",
  //   description: "Urban vibes for the concrete jungle.",
  //   coverImage: "/images/snm22.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX3Ogo9pFvBkY",
  //   tags: ["city", "urban", "modern", "energetic", "vibrant"],
  // },
  // {
  //   id: "spring",
  //   title: "Spring",
  //   description: "Fresh and blooming sounds of spring.",
  //   coverImage: "/images/snm23.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX4PP3DA4J0N8",
  //   tags: ["spring", "fresh", "bloom", "renewal", "light"],
  // },
  // {
  //   id: "summer",
  //   title: "Summer",
  //   description: "Hot and vibrant summer anthems.",
  //   coverImage: "/images/snm24.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX6FpkH3e3JwS",
  //   tags: ["summer", "hot", "vibrant", "energetic", "bright"],
  // },
  // {
  //   id: "autumn",
  //   title: "Autumn",
  //   description: "Golden and mellow autumn melodies.",
  //   coverImage: "/images/snm25.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DWWQRwui0ExPn",
  //   tags: ["autumn", "golden", "mellow", "warm", "cozy"],
  // },
  // {
  //   id: "winter",
  //   title: "Winter",
  //   description: "Cozy and warm winter tunes.",
  //   coverImage: "/images/snm26.png",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX1n9whBbBKoL",
  //   tags: ["winter", "cozy", "warm", "peaceful", "calm"],
  // },
  // {
  //   id: "rain",
  //   title: "rain",
  //   description: "Peaceful sounds for rainy days.",
  //   coverImage: "https://i.scdn.co/image/ab67706c0000da84c7c0c0c0c0c0c0c0c0c0c0c0",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX4PP3DA4J0N8",
  //   tags: ["Rain", "Peaceful", "Calm"],
  // },
  // {
  //   id: "snow",
  //   title: "snow",
  //   description: "Crisp and magical winter wonderland sounds.",
  //   coverImage: "https://i.scdn.co/image/ab67706c0000da84c7c0c0c0c0c0c0c0c0c0c0c0",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX1n9whBbBKoL",
  //   tags: ["Snow", "Winter", "Magical"],
  // },
  // {
  //   id: "storm",
  //   title: "storm",
  //   description: "Powerful and dramatic storm-inspired tracks.",
  //   coverImage: "https://i.scdn.co/image/ab67706c0000da84c7c0c0c0c0c0c0c0c0c0c0c0",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DWZwtERXCS82H",
  //   tags: ["Storm", "Dramatic", "Powerful"],
  // },
  // {
  //   id: "wind",
  //   title: "wind",
  //   description: "Flowing and ethereal wind-inspired melodies.",
  //   coverImage: "https://i.scdn.co/image/ab67706c0000da84c7c0c0c0c0c0c0c0c0c0c0c0",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX1n9whBbBKoL",
  //   tags: ["Wind", "Flowing", "Ethereal"],
  // },
  // {
  //   id: "clouds",
  //   title: "clouds",
  //   description: "Dreamy and floating cloud-like sounds.",
  //   coverImage: "https://i.scdn.co/image/ab67706c0000da84c7c0c0c0c0c0c0c0c0c0c0c0",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX4PP3DA4J0N8",
  //   tags: ["Clouds", "Dreamy", "Floating"],
  // },
  // {
  //   id: "stars",
  //   title: "stars",
  //   description: "Twinkling and cosmic starry night sounds.",
  //   coverImage: "https://i.scdn.co/image/ab67706c0000da84c7c0c0c0c0c0c0c0c0c0c0c0",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX1n9whBbBKoL",
  //   tags: ["Stars", "Cosmic", "Night"],
  // },
  // {
  //   id: "moon",
  //   title: "moon",
  //   description: "Lunar-inspired melodies for moonlit nights.",
  //   coverImage: "https://i.scdn.co/image/ab67706c0000da84c7c0c0c0c0c0c0c0c0c0c0c0",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX1n9whBbBKoL",
  //   tags: ["Moon", "Night", "Lunar"],
  // },
  // {
  //   id: "dawn",
  //   title: "dawn",
  //   description: "Gentle sounds for the first light of day.",
  //   coverImage: "https://i.scdn.co/image/ab67706c0000da84c7c0c0c0c0c0c0c0c0c0c0c0",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX4PP3DA4J0N8",
  //   tags: ["Dawn", "Morning", "Gentle"],
  // },
  // {
  //   id: "dusk",
  //   title: "dusk",
  //   description: "Transitional tunes for the end of day.",
  //   coverImage: "https://i.scdn.co/image/ab67706c0000da84c7c0c0c0c0c0c0c0c0c0c0c0",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX6FpkH3e3JwS",
  //   tags: ["Dusk", "Evening", "Transition"],
  // },
  // {
  //   id: "midnight",
  //   title: "midnight",
  //   description: "Deep and mysterious midnight sounds.",
  //   coverImage: "https://i.scdn.co/image/ab67706c0000da84c7c0c0c0c0c0c0c0c0c0c0c0",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX1n9whBbBKoL",
  //   tags: ["Midnight", "Deep", "Mysterious"],
  // },
  // {
  //   id: "noon",
  //   title: "noon",
  //   description: "Bright and energetic midday melodies.",
  //   coverImage: "https://i.scdn.co/image/ab67706c0000da84c7c0c0c0c0c0c0c0c0c0c0c0",
  //   spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX8NTLI2TtZa6",
  //   tags: ["Noon", "Bright", "Energetic"],
  // }
]
